name: docker
on: push
jobs: 
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build image
              run: docker build -t my_custom_python .

            - name: Run container in background 
              run: docker run -d --name my-python-app -p 8080:8000 my_custom_python

            - name: Wait for server and test with curl
              run: |
                sleep 3
                docker logs my-python-app
                curl --retry 5 --retry-connrefused --retry-delay 1 http://localhost:8080

            - name: Stop and remove container
              if: always()
              run: docker rm -f my-python-app
