name: docker
on: push
jobs: 
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker run hello-world
            - run: docker build -t my_custom_python .
            - run: bash container.sh
