name: docker
on: push
jobs: 
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Run image.sh (first time)
              run: bash image.sh

            - name: Run image.sh (second time)
              run: bash image.sh

